### ISSUE TITLE
Error message color leaks 

### ISSUE THREAD

**Issue by musm** [nickcox/pure-pwsh#11]
![image](https://user-images.githubusercontent.com/4319522/55889953-e277ff80-5b7f-11e9-9c78-5a4066cbf3b1.png)

Note how the prompt color got modified by the color of the error message

**Comment by nickcox** [comment]
What colour is `$pure.ErrorColor`? It should default to red.

**Comment by musm** [comment]
![image](https://user-images.githubusercontent.com/4319522/55924549-5219d900-5bd8-11e9-8cf8-1582bfc0c2cd.png)

**Comment by nickcox** [comment]
That looks correct. PowerShell doesn't change the value of `$?` unless you type some non-whitespace at the prompt.

**Comment by musm** [comment]
This behavior is not exhibited by default prompt however.

E.g.


![](https://i.imgur.com/aZ7vkSk.gif)

**Comment by nickcox** [comment]
Yeah, it's a feature of [pure](https://github.com/sindresorhus/pure). If you don't like it, just configure `$pure.ErrorColor` to white or whatever you prefer.

**Comment by musm** [comment]
ah OK thanks
