### ISSUE TITLE
Janky git prompt refresh 

### ISSUE THREAD

**Issue by musm** [nickcox/pure-pwsh#12]
Reproduction:

 

![](https://i.imgur.com/oRkaWgH.jpg)

Note: without using pure-pwsh git interacts   without issues.

**Comment by nickcox** [comment]
Yes, this needs fixing too. 🙉 

Could you try, `Set-PSReadLineOption -ExtraPromptLineCount 1`?

**Comment by nickcox** [comment]
Published as [0.6.2](https://www.powershellgallery.com/packages/pure-pwsh/0.6.2).

**Comment by musm** [comment]
Hmm, git prompt still does not refresh when it should

**Comment by nickcox** [comment]
Do you have an example?

**Comment by musm** [comment]
![](https://i.imgur.com/3brDevu.gif)

**Comment by nickcox** [comment]
There's a 2½ second throttle, so it won't update right away. Perhaps you type much faster than me. 😆

It does seem to take longer than that in your video though. Is it running at original speed?

**Comment by musm** [comment]
yep original speed. The reason I bring it up, is with my prompt the refresh is way faster. I'll try to also post a gif

**Comment by musm** [comment]
Can't we update the throttle so something smaller or is there a big disadvantage to doing so? 2 1/2 seconds seems too much.

**Comment by nickcox** [comment]
The disadvantage is that if the async handler kicks in while your command is still running (which can easily happen with long running commands like `git pull`) and we try to rewrite the prompt while the command is writing output then they can get in each other's way.

The right way to fix this is to do the update in the `OnIdle` event but there's currently a [bug in PSReadLine](https://github.com/lzybkr/PSReadLine/issues/827) that prevents the event from firing.

Not sure if there's much we can do until that's fixed. I could make the throttle configurable, I guess.

**Comment by musm** [comment]
Nice, the bug in PSReadline is fixed!

**Comment by musm** [comment]
Should we open a new issue to use `OnIdle` when a new version of  PSReadline is released ?

**Comment by nickcox** [comment]
It's a good idea. At the current cadence, I don't particularly expect a release anytime soon though.

**Comment by nickcox** [comment]
I was wrong about the PSReadLine release cycle - they released a beta just a couple of weeks after my previous comment. 😆 

FYI, there's a beta with support for the `OnIdle` fix [here](https://www.powershellgallery.com/packages/pure-pwsh/0.7.0-beta1). Obviously, it requires beta4 or above of PSReadLine in order to work properly.
