### ISSUE TITLE
Ctrl + L clearing console leaves an additional line

### ISSUE THREAD

**Issue by musm** [nickcox/pure-pwsh#15]
I'm not sure if this is at all related to  https://github.com/nickcox/pure-pwsh/issues/8 . But pressing Ctrl  + L leaves an additional line, which might be related to some miscalculation of the console prompt height.

**Comment by musm** [comment]
Yeah I'm also seeing some odd behavior with respect to clearing the console and interactions with other console applications such as julia. I'm not sure how to best demonstrate the bugs.

**Comment by nickcox** [comment]
Most likely we've not set PSReadLine's `ExtraPromptLineCount` correctly. What's your prompt and what is `(Get-PSReadLineOption).ExtraPromptLineCount`?

**Comment by musm** [comment]
My full prompt customizations are
```

function ShortenPath([string] $path) {
    $loc = $path.Replace($HOME, '~')
    # remove prefix for UNC paths
    $loc = $loc -replace '^[^:]+::', ''
    # make path shorter like tabs in Vim,
    # handle paths starting with \\ and . correctly
    return ($loc -replace '\\(\.?)([^\\])[^\\]*(?=\\)', '\$1$2')
}


Import-Module pure-pwsh
$myColors = @{DeepSkyBlue3 = "`e[38;5;31m"; DeepSkyBlue4 = "`e[38;5;23m"}

$pure.PwdFormatter = {ShortenPath $args}
$pure.PwdColor = $myColors.DeepSkyBlue4
$pure.BranchColor = '38;5;2m'
$pure.PromptChar = ">"
$pure.PromptColor = '38;5;15m'
$pure.PrePrompt = {
    param ($cwd, $git, $slow)
    "$($myColors.DeepSkyBlue3)$([Environment]::UserName) $cwd $git`n"
}

```

**Comment by musm** [comment]
In particular, a lot of these issues arise when resizing the console and hitting Ctrl + L after long outputs.

**Comment by musm** [comment]
Without your package
(Get-PSReadLineOption).ExtraPromptLineCount = 0
with your package 
(Get-PSReadLineOption).ExtraPromptLineCount = 2

**Comment by nickcox** [comment]
Hmmmm. Which version do you have?

```
Get-Module pure-pwsh | select Version
```

**Comment by musm** [comment]
0.6.2

**Comment by nickcox** [comment]
Not sure what's going on there then. When I copy/paste your settings as given above, my `ExtraPromptLineCount` is correctly updated to `1`.

```sh

~\projects\pure-pwsh master*
❯ (Get-PSReadLineOption).ExtraPromptLineCount
2

~\projects\pure-pwsh master*
❯ function ShortenPath([string] $path) {
❯❯     $loc = $path.Replace($HOME, '~')
❯❯     # remove prefix for UNC paths
❯❯     $loc = $loc -replace '^[^:]+::', ''
❯❯     # make path shorter like tabs in Vim,
❯❯     # handle paths starting with \\ and . correctly
❯❯     return ($loc -replace '\\(\.?)([^\\])[^\\]*(?=\\)', '\$1$2')
❯❯ }

~\projects\pure-pwsh master*
❯ $myColors = @{DeepSkyBlue3 = "`e[38;5;31m"; DeepSkyBlue4 = "`e[38;5;23m"}
❯❯
❯❯ $pure.PwdFormatter = {ShortenPath $args}
❯❯ $pure.PwdColor = $myColors.DeepSkyBlue4
❯❯ $pure.BranchColor = '38;5;2m'
❯❯ $pure.PromptChar = ">"
❯❯ $pure.PromptColor = '38;5;15m'
❯❯ $pure.PrePrompt = {
❯❯     param ($cwd, $git, $slow)
❯❯     "$($myColors.DeepSkyBlue3)$([Environment]::UserName) $cwd $git`n"
❯❯ }
Nick ~\p\pure-pwsh master*
> (Get-PSReadLineOption).ExtraPromptLineCount
1
```

You could try setting it manually as a workaround.

```
Set-PSReadLineOption -ExtraPromptLineCount 1
```

**Comment by musm** [comment]
That works

**I believe the issue was I had a comment on a new line in my prompt command. 
The comment seems to have lead to a miscalculation of the prompt height.**

**Comment by nickcox** [comment]
Awesome. Are you able to share the prompt that wasn't working? Sounds like it might be worth fixing if this is a bug.
