### ISSUE TITLE
Performance optimization

### ISSUE THREAD

**Issue by musm** [nickcox/pure-pwsh#18]
Anyway we could performance optimize the module so it starts up faster?

**Comment by nickcox** [comment]
I definitely want it to start up as fast as possible and I expect that it could be improved. On my machine it takes less than half a second though, which doesn't seem too bad.

How long is it in your environment? Which version are you using?

**Comment by musm** [comment]
Yeah I see roughly the same performance hit. 
PowerShell 6.2.3

Unfortunately my total profile load time is brutal at 4 seconds. Powershell takes about 700ms to start, plus the posh-git load times, and then sooner than later it's a total of 4 seconds.

**Comment by nickcox** [comment]
Having had a look, I'm not sure there's any obvious low hanging fruit.

Personally, I'm considering not loading `posh-git` in my profile and just bringing it in when I need it instead. (Although it's already loads faster than it used to be.)

Have you tried [beta2](https://www.powershellgallery.com/packages/pure-pwsh/0.7.0-beta2)? You might find it marginally faster.

**Comment by nickcox** [comment]
Closing this for now. Happy to investigate further if anyone has suggestions though.
