### ISSUE TITLE
Garbled prompt when using pure-pwsh via SSH

### ISSUE THREAD

**Issue by Calinou** [nickcox/pure-pwsh#4]
I'm hosting an OpenSSH server using the official Microsoft-supplied port on Windows 10 build 17134. When I connect to it from my Linux PC and start PowerShell, the prompt is garbled (but the rest is fine); I tried both kitty and Konsole to rule out a terminal-specific issue.

This does not occur in cmd.exe or PowerShell with the default prompt. See below for an example (look how the prompt is moved to the right):

![image](https://user-images.githubusercontent.com/180032/49477331-e33d0580-f81c-11e8-868d-2c3a4161ef59.png)

**Comment by nickcox** [comment]
Mmmmm. Not sure where to start with this one, tbh. Is it possible to capture a log file from the terminal to see what escape codes are actually being sent by OpenSSH? It looks as though there have been [issues in the past](https://github.com/PowerShell/Win32-OpenSSH/issues/1005).

You could also try upgrading to the latest non-bundled version. It's on Chocolatey as `openssh` and has been much more up to date and reliable than the version packaged with Windows for me.

**Comment by nickcox** [comment]
Closing this pending any further suggestions. Feel free to reopen if it's still an issue.
