### ISSUE TITLE
Customization question

### ISSUE THREAD

**Issue by musm** [nickcox/pure-pwsh#7]
`$pure.PrePrompt=  {param ($cwd, $git, $slow) "$([Environment]::UserName) $cwd $git $slow"}`

How would I go about colors my username with the same color used for cwd ?

Additionally how would I go about customizing other default colors

**Comment by nickcox** [comment]
Thanks for the question; I should add this to the documentation.

You could do this:

```sh
$pure.PrePrompt=
  {param ($cwd, $git, $slow) "$($pure._pwdColor)$([Environment]::UserName) $cwd $git $slow"}
```

**Comment by musm** [comment]
Thanks, another noob question: How do I go about changing the default colors as well?

**Comment by nickcox** [comment]
Yes, I need to document this too. 😄 

You just need to provide an [ANSI escape code](https://en.wikipedia.org/wiki/ANSI_escape_code#Colors), with or without the initial `ESC[`. So, for example, to set the PWD colour to red:

```sh
$pure.PwdColor = '31m'
```
 or '[deep sky blue 3](https://jonasjacek.github.io/colors/)':

```sh
$pure.PwdColor = '38;5;31m'
```

**Comment by musm** [comment]
Great thanks. 

How would I go about adding an additional color that goes through pure's color processing of the ansi escape sequences?

E.g.

` $pure.Mycolor = '38;5;31m'`  
so that I can use it for coloring additional elements in the prompt.

**Comment by nickcox** [comment]
There's no provision for additional colours, you'd have to include the escape code yourself. On PowerShell 6 you can just use `` `e[ ``.

```
myColours = @{ blue = "`e[38;5;31m" }

$pure.PrePrompt =
  {param ($cwd, $git, $slow) "$($myColours.blue)$([Environment]::UserName) $cwd $git $slow"}
```

**Comment by musm** [comment]
Thanks
